"""add table relative

Revision ID: 3c44f5eb0e8c
Revises: 
Create Date: 2023-05-24 13:58:31.337571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c44f5eb0e8c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_chats_id'), ['id'])

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chatid', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_conversations_id'), ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_conversations_chatid_chats'), 'chats', ['chatid'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_conversations_chatid_chats'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('uq_conversations_id'), type_='unique')
        batch_op.drop_column('chatid')

    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_chats_id'), type_='unique')

    # ### end Alembic commands ###
